#!/bin/bash
# As this call trayer-factory
#   there should be only one instance
#   of trayer running at a time
killall trayer

sleep 1 # wait for xmobar to run first

trayer \
--edge top \
--align center \
--margin 0 \
--widthtype percent \
--width 10 \
--heighttype pixel \
--height 17 \
--SetDockType true \
--SetPartialStrut true \
--transparent true \
--alpha 0 \
--tint 0x000000
--distance 0 \
--expand true \
--padding 0 \
&>/dev/null &
